Require jq and fix indents

diff --git a/bin/ecs-deploy b/bin/ecs-deploy
--- a/bin/ecs-deploy
+++ b/bin/ecs-deploy
@@ -1,40 +1,41 @@
 #!/usr/bin/env bash
 
 # forked from https://github.com/silinternational/ecs-deploy
+command -v jq > /dev/null 2>&1 || { echo >&2 'jq is required - install it!'; exit 2; }
 
 function usage() {
-    set -e
-    cat <<EOM
-    ##### ecs-deploy #####
-    Simple script for triggering blue/green deployments on Amazon Elastic Container Service
-    https://github.com/silinternational/ecs-deploy
-    Required arguments:
-        -k | --aws-access-key   AWS Access Key ID. May also be set as environment variable AWS_ACCESS_KEY_ID
-        -s | --aws-secret-key   AWS Secret Access Key. May also be set as environment variable AWS_SECRET_ACCESS_KEY
-        -r | --region           AWS Region Name. May also be set as environment variable AWS_DEFAULT_REGION
-        -p | --profile          AWS Profile to use - If you set this aws-access-key, aws-secret-key and region are needed
-  -c | --cluster          Name of ECS cluster
-        -n | --service-name     Name of service to deploy
-        -i | --image            Name of Docker image to run, ex: repo/image:latest
-                                Format: [domain][:port][/repo][/][image][:tag]
-                                Examples: mariadb, mariadb:latest, silintl/mariadb,
-                                          silintl/mariadb:latest, private.registry.com:8000/repo/image:tag
-    Optional arguments:
-        -t | --timeout          Default is 90s. Script monitors ECS Service for new task definition to be running.
-        -e | --tag-env-var      Get image tag name from environment variable. If provided this will override value specified in image name argument.
-        -v | --verbose          Verbose output
-    Examples:
-      Simple (Using env vars for AWS settings):
-        ecs-deploy -c production1 -n doorman-service -i docker.repo.com/doorman:latest
-      All options:
-        ecs-deploy -k ABC123 -s SECRETKEY -r us-east-1 -c production1 -n doorman-service -i docker.repo.com/doorman -t 240 -e CI_TIMESTAMP -v
-  Using profiles (for STS delegated credentials, for instance):
-        ecs-deploy -p PROFILE -c production1 -n doorman-service -i docker.repo.com/doorman -t 240 -e CI_TIMESTAMP -v
-    Notes:
-      - If a tag is not found in image and an ENV var is not used via -e, it will default the tag to "latest"
+  set -e
+  cat <<EOM
+  ##### ecs-deploy #####
+  Simple script for triggering blue/green deployments on Amazon Elastic Container Service
+  https://github.com/silinternational/ecs-deploy
+  Required arguments:
+    -k | --aws-access-key   AWS Access Key ID. May also be set as environment variable AWS_ACCESS_KEY_ID
+    -s | --aws-secret-key   AWS Secret Access Key. May also be set as environment variable AWS_SECRET_ACCESS_KEY
+    -r | --region           AWS Region Name. May also be set as environment variable AWS_DEFAULT_REGION
+    -p | --profile          AWS Profile to use - If you set this aws-access-key, aws-secret-key and region are needed
+    -c | --cluster          Name of ECS cluster
+    -n | --service-name     Name of service to deploy
+    -i | --image            Name of Docker image to run, ex: repo/image:latest
+                            Format: [domain][:port][/repo][/][image][:tag]
+                            Examples: mariadb, mariadb:latest, silintl/mariadb,
+                                      silintl/mariadb:latest, private.registry.com:8000/repo/image:tag
+  Optional arguments:
+    -t | --timeout          Default is 90s. Script monitors ECS Service for new task definition to be running.
+    -e | --tag-env-var      Get image tag name from environment variable. If provided this will override value specified in image name argument.
+    -v | --verbose          Verbose output
+  Examples:
+    Simple (Using env vars for AWS settings):
+      ecs-deploy -c production1 -n doorman-service -i docker.repo.com/doorman:latest
+    All options:
+      ecs-deploy -k ABC123 -s SECRETKEY -r us-east-1 -c production1 -n doorman-service -i docker.repo.com/doorman -t 240 -e CI_TIMESTAMP -v
+    Using profiles (for STS delegated credentials, for instance):
+      ecs-deploy -p PROFILE -c production1 -n doorman-service -i docker.repo.com/doorman -t 240 -e CI_TIMESTAMP -v
+  Notes:
+    If a tag is not found in image and an ENV var is not used via -e, it will default the tag to "latest"
 EOM
 
-    exit 2
+  exit 2
 }
 
 if [ $# == 0 ]; then usage; fi
@@ -52,54 +53,54 @@ AWS_ECS="$AWS_CLI --output json ecs"
 # Loop through arguments, two at a time for key and value
 while [[ $# > 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        -k|--aws-access-key)
-            AWS_ACCESS_KEY_ID="$2"
-            shift # past argument
-            ;;
-        -s|--aws-secret-key)
-            AWS_SECRET_ACCESS_KEY="$2"
-            shift # past argument
-            ;;
-  -r|--region)
+  case $key in
+    -k|--aws-access-key)
+      AWS_ACCESS_KEY_ID="$2"
+      shift # past argument
+      ;;
+    -s|--aws-secret-key)
+      AWS_SECRET_ACCESS_KEY="$2"
+      shift # past argument
+      ;;
+    -r|--region)
       AWS_DEFAULT_REGION="$2"
       shift # past argument
       ;;
-  -p|--profile)
+    -p|--profile)
       AWS_PROFILE="$2"
       shift # past argument
       ;;
-        -c|--cluster)
-            CLUSTER="$2"
-            shift # past argument
-            ;;
-        -n|--service-name)
-            SERVICE="$2"
-            shift # past argument
-            ;;
-        -i|--image)
-            IMAGE="$2"
-            shift
-            ;;
-        -t|--timeout)
-            TIMEOUT="$2"
-            shift
-            ;;
-        -e|--tag-env-var)
-            TAGVAR="$2"
-            shift
-            ;;
-        -v|--verbose)
-            VERBOSE=true
-            ;;
-        *)
-            usage
-            exit 2
-        ;;
-    esac
-    shift # past argument or value
+    -c|--cluster)
+      CLUSTER="$2"
+      shift # past argument
+      ;;
+    -n|--service-name)
+      SERVICE="$2"
+      shift # past argument
+      ;;
+    -i|--image)
+      IMAGE="$2"
+      shift
+      ;;
+    -t|--timeout)
+      TIMEOUT="$2"
+      shift
+      ;;
+    -e|--tag-env-var)
+      TAGVAR="$2"
+      shift
+      ;;
+    -v|--verbose)
+      VERBOSE=true
+      ;;
+    *)
+      usage
+      exit 2
+      ;;
+  esac
+  shift # past argument or value
 done
 
 # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION and AWS_PROFILE can be set as environment variables
@@ -107,43 +108,41 @@ if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then unset AWS_ACCESS_KEY_ID; fi
 if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then unset AWS_SECRET_ACCESS_KEY; fi
 if [ -z ${AWS_DEFAULT_REGION+x} ];
   then unset AWS_DEFAULT_REGION
-  else
-          AWS_ECS="$AWS_ECS --region $AWS_DEFAULT_REGION"
+  else AWS_ECS="$AWS_ECS --region $AWS_DEFAULT_REGION"
 fi
 if [ -z ${AWS_PROFILE+x} ];
   then unset AWS_PROFILE
-  else
-          AWS_ECS="$AWS_ECS --profile $AWS_PROFILE"
+  else AWS_ECS="$AWS_ECS --profile $AWS_PROFILE"
 fi
 
 if [ $VERBOSE == true ]; then
-    set -x
+  set -x
 fi
 
 # Make sure we have all the variables needed: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, CLUSTER, SERVICE, IMAGE
 if [ -z $AWS_ACCESS_KEY_ID ] && [ -z $AWS_PROFILE ]; then
-    echo "AWS_ACCESS_KEY_ID is required. You can set it as an environment variable or pass the value using -k or --aws-access-key"
-    exit 1
+  echo "AWS_ACCESS_KEY_ID is required. You can set it as an environment variable or pass the value using -k or --aws-access-key"
+  exit 1
 fi
 if [ -z $AWS_SECRET_ACCESS_KEY ] && [ -z $AWS_PROFILE ]; then
-    echo "AWS_SECRET_ACCESS_KEY is required. You can set it as an environment variable or pass the value using -s or --aws-secret-key"
-    exit 1
+  echo "AWS_SECRET_ACCESS_KEY is required. You can set it as an environment variable or pass the value using -s or --aws-secret-key"
+  exit 1
 fi
 if [ -z $AWS_DEFAULT_REGION ] && [ -z $AWS_PROFILE ]; then
-    echo "AWS_DEFAULT_REGION is required. You can set it as an environment variable or pass the value using -r or --region"
-    exit 1
+  echo "AWS_DEFAULT_REGION is required. You can set it as an environment variable or pass the value using -r or --region"
+  exit 1
 fi
 if [ $CLUSTER == false ]; then
-    echo "CLUSTER is required. You can pass the value using -c or --cluster"
-    exit 1
+  echo "CLUSTER is required. You can pass the value using -c or --cluster"
+  exit 1
 fi
 if [ $SERVICE == false ]; then
-    echo "SERVICE is required. You can pass the value using -n or --service-name"
-    exit 1
+  echo "SERVICE is required. You can pass the value using -n or --service-name"
+  exit 1
 fi
 if [ $IMAGE == false ]; then
-    echo "IMAGE is required. You can pass the value using -i or --image"
-    exit 1
+  echo "IMAGE is required. You can pass the value using -i or --image"
+  exit 1
 fi
 
 # Define regex for image name
